# ──────────────────────────────────────────────
# Release Pipeline — DEX Exchange
# Triggered on version tags: v*.*.*
# Build → Push → Deploy to staging
# ──────────────────────────────────────────────
name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  # ─── Run all tests first ───────────────────
  test:
    name: Pre-release Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: gateway, path: services/gateway }
          - { name: matching-engine, path: services/matching-engine }
          - { name: market-data, path: services/market-data }
          - { name: risk-engine, path: services/risk-engine }
          - { name: persistence, path: services/persistence }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run tests
        working-directory: ${{ matrix.service.path }}
        run: cargo test --all-features

      - name: Clippy
        working-directory: ${{ matrix.service.path }}
        run: cargo clippy --all-features -- -D warnings

  # ─── Build & push release images ───────────
  release-images:
    name: Build Release Images
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [gateway, matching-engine, market-data, risk-engine, persistence]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.${{ matrix.service }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ steps.version.outputs.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ─── Deploy to staging ─────────────────────
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: release-images
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > ~/.kube/config

      - name: Update image tags
        run: |
          for svc in gateway matching-engine market-data risk-engine persistence; do
            kubectl -n dex-exchange-staging set image \
              deployment/$svc \
              $svc=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/$svc:${{ steps.version.outputs.VERSION }}
          done

      - name: Wait for rollout
        run: |
          for svc in gateway matching-engine market-data risk-engine persistence; do
            kubectl -n dex-exchange-staging rollout status deployment/$svc --timeout=300s
          done

      - name: Verify health
        run: |
          sleep 10
          for port in 8080 8081 8082 8083 8084; do
            echo "Checking health on port $port..."
          done

  # ─── Create GitHub Release ─────────────────
  github-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: deploy-staging
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
